"""initial schema

Revision ID: 2b7806a018fc
Revises: 
Create Date: 2026-09-13 22:34:28.084212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b7806a018fc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_corpus',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('section_number', sa.String(length=100), nullable=True),
    sa.Column('jurisdiction', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=30), nullable=False),
    sa.Column('court', sa.String(length=150), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('lawyer', 'client', 'student', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('otp', sa.String(length=6), nullable=True),
    sa.Column('otp_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cases',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('case_type', sa.Enum('custody', 'inheritance', 'divorce', 'maintenance', name='case_type'), nullable=False),
    sa.Column('status', sa.Enum('created', 'assigned', 'in_progress', 'hearing_scheduled', 'closed', name='case_status'), nullable=False),
    sa.Column('court_code', sa.String(length=60), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('assigned_lawyer_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('client_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_lawyer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('cnic', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnic'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('lawyers',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('bar_license_no', sa.String(length=50), nullable=False),
    sa.Column('specialization', sa.String(length=120), nullable=False),
    sa.Column('bar_year', sa.Integer(), nullable=False),
    sa.Column('bar_council', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bar_license_no'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('students',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('university_id', sa.String(length=50), nullable=False),
    sa.Column('university_name', sa.String(length=150), nullable=False),
    sa.Column('current_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('university_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('case_participants',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('role_in_case', sa.Enum('lawyer', 'client', 'witness', 'judge', name='role_in_case'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('user_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('language_hint', sa.String(length=10), nullable=True),
    sa.Column('total_messages', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('uploaded_by_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('file_type', sa.Enum('pdf', 'docx', 'txt', 'png', 'jpg', name='file_type'), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('document_type', sa.Enum('other', name='document_type'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('summary_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('session_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('sender_type', sa.Enum('user', 'ai', name='sender_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('detected_language', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('document_analysis',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('document_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('identified_clauses', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('document_classification', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_analysis')
    op.drop_table('chat_messages')
    op.drop_table('documents')
    op.drop_table('chat_sessions')
    op.drop_table('case_participants')
    op.drop_table('students')
    op.drop_table('lawyers')
    op.drop_table('clients')
    op.drop_table('cases')
    op.drop_table('activity_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('legal_corpus')
    # ### end Alembic commands ###
