"""add contracts and contract_versions tables

Revision ID: aab3307a5ca9
Revises: 16e7f2d6727c
Create Date: 2026-09-20 23:43:44.035448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aab3307a5ca9'
down_revision: Union[str, None] = '16e7f2d6727c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contracts',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('case_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=True),
    sa.Column('created_by_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('contract_type', sa.Enum('nda', 'employment', 'service_agreement', name='contract_type'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contract_versions',
    sa.Column('id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('contract_id', sa.UUID().with_variant(sa.Uuid(), 'sqlite'), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('compliance_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contract_id'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contract_versions')
    op.drop_table('contracts')
    # ### end Alembic commands ###
