import { AlertCircle, Sparkles, Tags } from "lucide-react";
import PanelCard from "@/features/dashboard/components/PanelCard";
import MarkdownBlocks from "@/lib/MarkdownBlocks";

// Display names for the NER model's entity types (backend app/ai/ner.py).
const ENTITY_LABELS = {
  per: "People",
  org: "Organisations",
  resp: "Respondents",
  date: "Dates",
  loc: "Places",
  money: "Amounts",
  caseno: "Case numbers",
  appealcaseno: "Case appealed from",
  appealcourt: "Court appealed from",
  refcase: "Cited cases",
  refcourt: "Cited courts",
  ref: "Statutory references",
  Approved: "Approved for reporting",
};

// Two sources, deliberately kept visually separate:
//   left  — written by the LLM (summary, clauses, risks)
//   right — extracted by the NER model (parties, dates, references, entities)
export default function AnalysisResults({ analysis }) {
  return (
    <div className="mt-10 grid gap-10 lg:grid-cols-2">
      <PanelCard
        title="AI summary"
        description="Written by the language model from the document text. Check it against the document before relying on it."
      >
        <SourceNote icon={Sparkles}>Generated by the language model</SourceNote>
        <div className="border border-hairline-subtle p-4 max-h-[28rem] overflow-y-auto">
          <MarkdownBlocks text={analysis.summary} />
        </div>
        <ItemList title="Key clauses" items={analysis.key_clauses} empty="The summary listed no key clauses." />
        <ItemList title="Risk flags" items={analysis.risks} empty="The summary listed no risks." />
      </PanelCard>

      <PanelCard
        title="Extracted entities"
        description="Found by LegalEase's entity-recognition model, trained on Pakistani court judgments. Most reliable on judgments; expect misses on contracts and other documents."
      >
        <SourceNote icon={Tags}>Extracted by the NER model — not the language model</SourceNote>
        {analysis.ner_available ? (
          <NerResults analysis={analysis} />
        ) : (
          <div className="flex items-start gap-2 py-4 text-sm text-ink-muted">
            <AlertCircle className="h-4 w-4 shrink-0 mt-0.5" />
            <p>
              The entity-recognition model isn't loaded on this server, so
              parties, dates and references weren't extracted. The AI summary
              is unaffected.
            </p>
          </div>
        )}
      </PanelCard>
    </div>
  );
}

function SourceNote({ icon: Icon, children }) {
  return (
    <p className="flex items-center gap-1.5 text-xs text-ink-muted py-3">
      <Icon className="h-3.5 w-3.5" />
      {children}
    </p>
  );
}

function NerResults({ analysis }) {
  const groups = Object.entries(analysis.entities || {});
  return (
    <>
      <div className="grid grid-cols-3 mb-2">
        <Stat label="Parties" value={analysis.parties.length} />
        <Stat label="Dates" value={analysis.dates.length} />
        <Stat label="References" value={analysis.references.length} last />
      </div>
      <ItemList title="Parties" items={analysis.parties} empty="No people or organisations found." />
      <ItemList title="Dates" items={analysis.dates} empty="No dates found." />
      <ItemList title="References" items={analysis.references} empty="No case numbers, cited cases or statutes found." />

      {groups.length > 0 && (
        <details className="mt-6 group">
          <summary className="cursor-pointer text-sm text-ink-text py-2 -mx-2 px-2 hover:bg-hairline-subtle/40">
            All entities by type ({groups.reduce((n, [, es]) => n + es.length, 0)})
          </summary>
          <table className="w-full text-left text-sm mt-2 border-t border-hairline">
            <thead>
              <tr className="border-b border-hairline text-ink-muted">
                <th className="py-2 pr-4 font-medium">Type</th>
                <th className="py-2 pr-4 font-medium">Text</th>
                <th className="py-2 pr-4 font-medium text-right">Mentions</th>
                <th className="py-2 font-medium text-right">Confidence</th>
              </tr>
            </thead>
            <tbody>
              {groups.flatMap(([type, ents]) =>
                ents.map((e, i) => (
                  <tr key={`${type}-${i}`} className="border-b border-hairline-subtle align-top">
                    <td className="py-2 pr-4 text-ink-muted whitespace-nowrap">
                      {i === 0 ? ENTITY_LABELS[type] || type : ""}
                    </td>
                    <td className="py-2 pr-4 text-ink-text">{e.text}</td>
                    <td className="py-2 pr-4 text-right text-ink-muted">{e.count}</td>
                    <td className="py-2 text-right text-ink-muted">{e.score.toFixed(2)}</td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </details>
      )}
    </>
  );
}

function ItemList({ title, items, empty }) {
  return (
    <div className="mt-6">
      <h3 className="text-sm font-medium text-ink-text mb-1">{title}</h3>
      {items.length === 0 ? (
        <p className="text-sm text-ink-muted py-2">{empty}</p>
      ) : (
        <ul className="border-t border-hairline-subtle">
          {items.map((it, i) => (
            <li key={i} className="py-2 border-b border-hairline-subtle text-sm text-ink-text">
              {it}
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function Stat({ label, value, last = false }) {
  return (
    <div className={`px-4 first:pl-0 py-1 ${last ? "" : "border-r border-hairline"}`}>
      <div className="text-xs text-ink-muted">{label}</div>
      <div className="text-sm font-medium text-ink-text mt-1">{value}</div>
    </div>
  );
}
